use_frameworks!

target 'RoundedUI_Example' do
  pod 'RoundedUI', :path => '../'
  pod 'PureLayout'

  target 'RoundedUI_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
