use_frameworks!

target 'RoundedUI_Example' do
  pod 'RoundedUI', :path => '../'

  target 'RoundedUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.3.3'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
